server:
  port: 40000
spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false
  rabbitmq:
    host: 112.126.59.115
    port: 5672
    listener:
      simple:
        #手动ack
        acknowledge-mode: manual
    #开启发送端确认
    publisher-confirms: true
    #开启抵达队列确认
    publisher-returns: true
    #只要抵达队列，以异步方式优先调用returnConfirm
    template:
      mandatory: true