server:
  port: 10001

spring:
  application:
    name: mall-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.126.59.115:3306/gulimall_pms?serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    #缓存类型
    type: redis
    redis:
      #redi缓存过期时间
      time-to-live: 600000
      #是否缓存空值，防止缓存穿透
      cache-null-values: true
      #开启缓存前缀
      use-key-prefix: true
      #缓存前缀
      #key-prefix: CACHE_
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  global-config:
    db-config:
      id-type: auto
      # 0表示逻辑删除
      logic-delete-value: 0
      # 1表示逻辑不删除
      logic-not-delete-value: 1
logging:
  level:
    com.mall: debug

product:
  thread:
    core-pool-size: 20
    maximum-pool-size: 50
    keep-alive-time: 10
    unit: seconds
    task-queue-capacity: 100000
