server:
  port: 30000
spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    cache: false

