server:
  port: 7000
spring:
  application:
    name: mall-coupon
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.126.59.115:3306/gulimall_sms?serverTimezone=GMT
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  mapper-locations: classpath://mapper/**.xml
  global-config:
    db-config:
      id-type: auto
